# Generated by Django 3.2.7 on 2023-01-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knox', '0007_auto_20190111_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnoxAuthToken',
            fields=[
                ('authtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knox.authtoken')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
            ],
            bases=('knox.authtoken',),
        ),
    ]
