# Generated by Django 3.2.11 on 2023-01-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH_ON_DELIVERY', 'CASH_ON_DELIVERY'), ('KHALTI', 'KHALTI')], max_length=20, null=True),
        ),
    ]
