# Generated by Django 3.2.11 on 2023-01-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20230116_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROCESS', 'IN_PROCESS'), ('ON_THE_WAY', 'ON_THE_WAY'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
    ]
