# Generated by Django 3.2.11 on 2023-01-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
