# Generated by Django 3.2.11 on 2023-02-01 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_alter_fileupload_created_by_and_more'),
        ('product', '0006_auto_20230118_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_category', to='commons.fileupload'),
        ),
    ]
