# Generated by Django 3.2.11 on 2023-01-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
