# Generated by Django 3.2.11 on 2023-01-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20230113_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetail',
            name='is_same_user',
        ),
    ]
