PENDING = 'PENDING'
IN_PROCESS = 'IN_PROCESS'
ON_THE_WAY = 'ON_THE_WAY'
DELIVERED = 'DELIVERED'
CANCELLED = 'CANCELLED'

STATUS_CHOICES = (
    (PENDING, 'PENDING'),
    (IN_PROCESS, 'IN_PROCESS'),
    (ON_THE_WAY, 'ON_THE_WAY'),
    (DELIVERED, 'DELIVERED'),
    (CANCELLED, 'CANCELLED')
)
CASH_ON_DELIVERY = 'CASH_ON_DELIVERY'
KHALTI = 'KHALTI'
PAYMENT_CHOICES = (
    (CASH_ON_DELIVERY, 'CASH_ON_DELIVERY'),
    (KHALTI, 'KHALTI')
)
