PENDING = 'PENDING'
IN_PROCESS = 'IN_PROCESS'
SHIPPED = 'SHIPPED'
DELIVERED = 'DELIVERED'
CANCELLED = 'CANCELLED'

STATUS_CHOICES = (
    (PENDING, 'PENDING'),
    (IN_PROCESS, 'IN_PROCESS'),
    (SHIPPED, 'SHIPPED'),
    (DELIVERED, 'DELIVERED'),
    (CANCELLED, 'CANCELLED')
)
CASH_ON_DELIVERY = 'CASH_ON_DELIVERY'
KHALTI = 'KHALTI'
PAYMENT_CHOICES = (
    (CASH_ON_DELIVERY, 'CASH_ON_DELIVERY'),
    (KHALTI, 'KHALTI')
)
