PENDING = 'PENDING'
IN_PROCESS = 'IN_PROCESS'
SHIPPED = 'SHIPPED'
DELIVERED = 'DELIVERED'
CANCELLED = 'CANCELLED'

STATUS_CHOICES = (
    (PENDING, 'PENDING'),
    (IN_PROCESS, 'IN_PROCESS'),
    (SHIPPED, 'SHIPPED'),
    (DELIVERED, 'DELIVERED'),
    (CANCELLED, 'CANCELLED')
)
